LIST P=18F4520
#include <p18f4520.inc>
#include "toolbelt.asm"
  CONFIG OSC = INTIO67
  CONFIG WDT = OFF
  org 0x00
  i EQU 0x30
;  j EQU 0x31
  limI EQU 0x32
  limJ EQU 0x33
  sum EQU 0x34
 LFSR 0, 0x200
 LFSR 1, 0x210
  GOTO main
;=============================  
;=============================
;  bodyLbl:
;    MOVFF i, POSTINC0
;    MOVFF j, POSTINC1
;    INCF sum, f
;    RETURN
  
;  #include "mul_extended.asm"
 #include "bubble_sort"
;EXTRN bubble_sort
;=============================
; MAIN PROGRAM
;=============================
main:
  MOVLF 0x01, POSTINC0
  MOVLF 0x03, POSTINC0
  MOVLF 0x05, POSTINC0
  MOVLF 0x07, POSTINC0
  MOVLF 0x09, POSTINC0
  MOVLF 0x0B, INDF0

  MOVLF 0x02, POSTINC1
  MOVLF 0x04, POSTINC1
  MOVLF 0x06, POSTINC1
  MOVLF 0x08, POSTINC1
  MOVLF 0x0A, INDF1

  LFSR    2, 0x020
  MOVFF POSTDEC0, POSTINC2
  MOVFF POSTDEC0, POSTINC2
  MOVFF POSTDEC0, POSTINC2
  MOVFF POSTDEC0, POSTINC2
  MOVFF POSTDEC0, POSTINC2
  MOVFF POSTDEC0, POSTINC2

  MOVFF POSTDEC1, POSTINC2
  MOVFF POSTDEC1, POSTINC2
  MOVFF POSTDEC1, POSTINC2
  MOVFF POSTDEC1, POSTINC2
  MOVFF POSTDEC1, POSTINC2
  
  MOVLW 0x20
  MOVWF   baseL
  MOVLW   d'11'
  MOVWF   len

  RCALL   bubble_sort

  LFSR 0, 0x220
  LFSR 2, 0x020
  MOVFF POSTINC2, POSTINC0
  MOVFF POSTINC2, POSTINC0
  MOVFF POSTINC2, POSTINC0
  MOVFF POSTINC2, POSTINC0
  MOVFF POSTINC2, POSTINC0
  MOVFF POSTINC2, POSTINC0
  MOVFF POSTINC2, POSTINC0
  MOVFF POSTINC2, POSTINC0
  MOVFF POSTINC2, POSTINC0
  MOVFF POSTINC2, POSTINC0
  MOVFF POSTINC2, POSTINC0
  
  NOP
  END