LIST p=18f4520
#include <p18f4520.inc>
#include "toolbelt.asm"
CONFIG OSC = INTIO67
CONFIG WDT = OFF

org 0x00
;=============================
; VARIABLES
;=============================
  cblock 0x20
      n
  endc
  LFSR 0, 0x030
  MOVLF 0x00, POSTINC0
  MOVLF 0x01, POSTINC0
  MOVLF 0x02, POSTINC0
  MOVLF 0x04, POSTINC0

  LFSR 1, 0x031
  LFSR 2, 0x034
  func macro 
    MOVFF   POSTINC1, INDF2
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF POSTINC2, f
 endm
  MOVLB 0x000
 MOVFF   POSTINC1, INDF2
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF POSTINC2, f
  
  MOVFF   POSTINC1, INDF2
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF POSTINC2, f
  
  MOVFF   POSTINC1, INDF2
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF POSTINC2, f
  
  MOVFF   POSTINC1, INDF2
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF POSTINC2, f
  
  MOVFF   POSTINC1, INDF2
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF POSTINC2, f
  
  MOVFF   POSTINC1, INDF2
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF POSTINC2, f
  
  MOVFF   POSTINC1, INDF2
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF POSTINC2, f
  
  MOVFF   POSTINC1, INDF2
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF INDF2, f
  MOVF INDF1, w
  ADDWF POSTINC2, f
; clrF bsr
 MOVLF d'9', n
 LFSR 0, 0x030
 MOVF n, w
 ADDWF FSR0L, f

 
 MOVF INDF0, W
 movwf 0x00
  
  NOP
    END
